name: Deploy to VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Debug SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "echo 'SSH Connection Successful!'"

      - name: Get Latest Tag from Docker Hub
        id: get-latest-tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/whatsapp-blast/tags?page_size=1" | jq -r '.results[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            echo "Login SSH berhasil!"
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/whatsapp-blast:$LATEST_TAG

            docker stop whatsapp-blast || true
            docker rm whatsapp-blast || true

            docker run -d --name whatsapp-blast --restart unless-stopped \
              --env-file /home/${{ secrets.VM_USER }}/whatsapp-blast/.env \
              -v /home/${{ secrets.VM_USER }}/whatsapp-blast/sessions:/app/sessions \
              -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/whatsapp-blast:$LATEST_TAG
          EOF
